### ISSUE TITLE
Use of template name "rowTemplate.html" conflicts with ng-grid

### ISSUE THREAD

**Issue by kwesterfeld** [hawtio/hawtio-forms#10]
The hawtio-form "array" template has a <tr> template for tabular representation that conflicts with the exact spelling used within ng-grid.   The template name is 'rowTemplate.html'.  

Basically, if you use ng-grid and hawtio-preferences/hawtio-forms together, after a form is rendered by hawtio-forms the grid content cannot be displayed on any grid until the template is reloaded (ie. page refresh)

**Comment by gashcrumb** [comment]
Should be an easy fix, we can just prefix the template name in hawtio-forms which should sort it out without breaking anything.
